In [1]:
import os
os.chdir('..')
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
from Preprocessing import MatchAnalyzer as ma
from Database import FootballDB

1. DB 인스턴스 생성

In [2]:
# db = FootballDB('localhost', 'postgres', 5432, 'udmt', 'football')
db = FootballDB('localhost', 'postgres', 5432, 'alsdud12', 'football')

2.  Season Table 불러오기

In [3]:
query = "SELECT * FROM tbl_season_position WHERE season='17-18'"
rows, cols = db.selectResult(query)
result = pd.DataFrame(data=rows, columns=cols)
result

,league,season,position,team,point,won,drawn,lost,gd,gf,ga,yellow,red
0,Premier League,17-18,1,Man City,100,32,4,2,79,106,27,58,2
1,Premier League,17-18,2,Man United,81,25,6,7,40,68,28,64,1
2,Premier League,17-18,3,Tottenham,77,23,8,7,38,74,36,49,2
3,Premier League,17-18,4,Liverpool,75,21,12,5,46,84,38,44,1
4,Premier League,17-18,5,Chelsea,70,21,7,10,24,62,38,41,4
5,Premier League,17-18,6,Arsenal,63,19,6,13,23,74,51,57,2
6,Premier League,17-18,7,Burnley,54,14,12,12,-3,36,39,65,0
7,Premier League,17-18,8,Everton,49,13,10,15,-14,44,58,51,3
8,Premier League,17-18,9,Leicester,47,12,11,15,-4,56,60,52,5
9,Premier League,17-18,10,Newcastle,44,12,8,18,-8,39,47,52,2
10,Premier League,17-18,11,Crystal Palace,44,11,11,16,-10,45,55,71,0
11,Premier League,17-18,12,Bournemouth,44,11,11,16,-16,45,61,55,1
12,Premier League,17-18,13,West Ham,42,10,12,16,-20,48,68,72,2
13,Premier League,17-18,14,Watford,41,11,8,19,-20,44,64,63,4
14,Premier League,17-18,15,Brighton,40,9,13,16,-20,34,54,54,2
15,Premier League,17-18,16,Huddersfield,37,9,10,19,-30,28,58,61,3
16,Premier League,17-18,17,Southampton,36,7,15,16,-19,37,56,63,2
17,Premier League,17-18,18,Swansea,33,8,9,21,-28,28,56,51,1
18,Premier League,17-18,19,Stoke,33,7,12,19,-33,35,68,62,1
19,Premier League,17-18,20,West Brom,31,6,13,19,-25,31,56,72,1

In [4]:
query = "SELECT * FROM tbl_season_position WHERE season='18-19'"
rows, cols = db.selectResult(query)
result = pd.DataFrame(data=rows, columns=cols)
result

,league,season,position,team,point,won,drawn,lost,gd,gf,ga,yellow,red
0,Premier League,18-19,1,Man City,98,32,2,4,72,95,23,44,1
1,Premier League,18-19,2,Liverpool,97,30,7,1,67,89,22,37,2
2,Premier League,18-19,3,Chelsea,72,21,9,8,24,63,39,49,0
3,Premier League,18-19,4,Tottenham,71,23,2,13,28,67,39,56,3
4,Premier League,18-19,5,Arsenal,70,21,7,10,22,73,51,72,2
5,Premier League,18-19,6,Man United,66,19,9,10,11,65,54,73,4
6,Premier League,18-19,7,Wolves,57,16,9,13,1,47,46,72,1
7,Premier League,18-19,8,Everton,54,15,9,14,8,54,46,55,4
8,Premier League,18-19,9,Leicester,52,15,7,16,3,51,48,57,5
9,Premier League,18-19,10,West Ham,52,15,7,16,-3,52,55,59,1
10,Premier League,18-19,11,Watford,50,14,8,16,-7,52,59,77,4
11,Premier League,18-19,12,Crystal Palace,49,14,7,17,-2,51,53,58,2
12,Premier League,18-19,13,Newcastle,45,12,9,17,-6,42,48,57,2
13,Premier League,18-19,14,Bournemouth,45,13,6,19,-14,56,70,60,1
14,Premier League,18-19,15,Burnley,40,11,7,20,-23,45,68,75,1
15,Premier League,18-19,16,Southampton,39,9,12,17,-20,45,65,71,3
16,Premier League,18-19,17,Brighton,36,9,9,20,-25,35,60,60,4
17,Premier League,18-19,18,Cardiff,34,10,4,24,-35,34,69,65,1
18,Premier League,18-19,19,Fulham,26,7,5,26,-47,34,81,68,2
19,Premier League,18-19,20,Huddersfield,16,3,7,28,-54,22,76,55,4

In [6]:
query = "SELECT * FROM tbl_season_position WHERE season='16-17'"
rows, cols = db.selectResult(query)
result = pd.DataFrame(data=rows, columns=cols)
result

,league,season,position,team,point,won,drawn,lost,gd,gf,ga,yellow,red
0,Premier League,16-17,1,Chelsea,93,30,3,5,52,85,33,72,0
1,Premier League,16-17,2,Tottenham,86,26,8,4,60,86,26,62,0
2,Premier League,16-17,3,Man City,78,23,9,6,41,80,39,71,4
3,Premier League,16-17,4,Liverpool,76,22,10,6,36,78,42,54,0
4,Premier League,16-17,5,Arsenal,75,23,6,9,33,77,44,67,3
5,Premier League,16-17,6,Man United,69,18,15,5,25,54,29,76,2
6,Premier League,16-17,7,Everton,61,17,10,11,18,62,44,71,2
7,Premier League,16-17,8,Southampton,46,12,10,16,-7,41,48,58,2
8,Premier League,16-17,9,Bournemouth,46,12,10,16,-12,55,67,51,3
9,Premier League,16-17,10,West Brom,45,12,9,17,-8,43,51,80,0
10,Premier League,16-17,11,West Ham,45,12,9,17,-17,47,64,77,5
11,Premier League,16-17,12,Leicester,44,12,8,18,-15,48,63,71,1
12,Premier League,16-17,13,Stoke,44,11,11,16,-15,41,56,70,2
13,Premier League,16-17,14,Crystal Palace,41,12,5,21,-13,50,63,77,0
14,Premier League,16-17,15,Swansea,41,12,5,21,-25,45,70,56,0
15,Premier League,16-17,16,Burnley,40,11,7,20,-16,39,55,65,2
16,Premier League,16-17,17,Watford,40,11,7,20,-28,40,68,83,5
17,Premier League,16-17,18,Hull,34,9,7,22,-43,37,80,67,5
18,Premier League,16-17,19,Middlesbrough,28,5,13,20,-26,27,53,76,1
19,Premier League,16-17,20,Sunderland,24,6,6,26,-40,29,69,76,4